### PR TITLE
perf: better concurrency & remove unnecessary deserialization

### PR DESCRIPTION
**Pull request by tien**

### CODE REVIEW

**Review by James-Sangalli — CHANGES_REQUESTED** [review]
Hi @tien, looks great!

I ran the test and noticed the following errors:

Screen Shot 2022-10-29 at 5 16 44 pm

Please correct this and sync with main. Thank you.

**Comment by tien** [comment]
> Hi @tien, looks great!
> 
> I ran the test and noticed the following errors:
> 
> Screen Shot 2022-10-29 at 5 16 44 pm
> 
> Please correct this and sync with main. Thank you.

Ooops, must have made some last minutes changes to the test without checking. Will have this sorted out tonight 💪

**Comment by tien** [comment]
@James-Sangalli Just noticed from the screenshot that your run took 3 minutes. I think you are running it on the wrong branch, because the tests suite should now take 10 seconds

**Comment by tien** [comment]
@James-Sangalli rebased with main & added the test to GitHub Action as well 💪

**Comment by James-Sangalli** [comment]
> @James-Sangalli rebased with main & added the test to GitHub Action as well 💪

Excellent work! I am able to run the tests in >20 seconds but the two errors in the tests persist. I am using commit aab64dd714e9cea9f616de23418fff31be057a76.

**Comment by tien** [comment]
@James-Sangalli hey the [check](https://github.com/TalismanSociety/dot-pool-selector/pull/13/checks) passed. And since I need this for nomination pools QA today, will have this merged now 💪

**Pull request merged**
